const fs = require('fs')
// const path = require('path')
// const argv = require('minimist')(process.argv.slice(2));

const array = [
    "",
    "A los Srs(as). David Callabuig Tortosa, Carlota Hernandez Hernandez y demás domiciliados en mi residencia fiscal, a saber: Carrer de Bismarck 11, 2-1 Barcelona 08024 España.",
    "",
    "Direcciones:",
    "",
    "- David / desconocido, agente inmobiliario, parte acusada;",
    "- Demás partes citadas, partes acusadas: Carrer de Bismarck 11, 2-1 Barcelona 08024 España;",
    "",
    "De:",
    "",
    "Angelo Reale Caldeira de Lemos",
    "",
    "Carrer de Bismarck 11, Barcelona",
    "",
    "Asunto: Notificación extrajudicial por delitos de agresión física, tortura y abusos psicológicos de vulnerables, estímulo al suicidio, sabotaje arbitrario de recursos de infraestructura básica (internet y electricidad), conducción coercitiva, detención ilícita en cautiverio privado, agravadas por conocimiento de condición psíquica caracterizada por el DSM-5 F30.10, así como impedimento criminal del pleno goce del derecho constitucional de libre movimiento, o habeas corpus, así como falsedad ideológica, intento de violación de domicilio, intento de incriminación, asociación criminal, negligencia al socorro emergencial, intimidación, violación de privacidad, violación de propiedad privada, ofensa, entre otros.",
    "",
    "Contenido:",
    "",
    "En vistas:",
    "",
    "1. Del inicio del contrato de alquiler regular de vivienda en Carrer de Bismarck 11, hecho jurídico ocurrido en marzo de 2024;",
    "2. Del pago regular de los emolumentos correspondientes al valor del alquiler dentro del plazo (excepto un único retraso de 5 días debido a eventos imprevistos de fuerza mayor, garantizados y subsidiados por el depósito de garantía) hasta la fecha actual, hecho jurídico ipso facto;",
    "3. De la constitución de domicilio legal y fiscal (por solicitud consular de inscripción anagráfica), hechos jurídicos ocurridos en abril de 2024.",
    "4. De la disfunción de irregularidad en la distribución del suministro de energía eléctrica en las instalaciones de la residencia desde la primera semana (caídas injustificadas), hechos jurídicos ocurridos en marzo de 2024.",
    "5. De la solicitud formal para aumentar la potencia nominal del suministro de energía eléctrica en la primera semana de la domiciliación, así como reiteradas solicitudes/recordatorios para garantizar la conclusión del procedimiento, y la falsa justificación por parte del agente inmobiliario de que el procedimiento no era inmediato (y que llevaría meses), así como del conocimiento de que el mismo procedimiento suele concluirse el mismo día para la mayoría de las compañías eléctricas europeas, así como mi intento de notificar a las autoridades del posible delito de 264 y 264bis del CP Español a través del 112, en función de los mismos hechos, hechos jurídicos ocurridos en abril/2024;",
    "6. Del compartimiento de mi condición de F30.10 (DSM-5), ocurrido en abril/2024;",
    "7. De la violación de mi privacidad, invadiendo el baño común mientras me duchaba, y la violación de propiedad privada, al apagar mi altavoz JBL Flip 5 sin mi consentimiento, cometido por Kory y respaldado por los cohabitantes, así como mi intento de notificar a las fuerzas del orden a través del 112, que no comparecieron, o no tomaron mi declaración de los hechos, hechos jurídicos ocurridos en abril/2024;",
    "8. De la exigencia ilegal e injustificada para que dejara mi residencia inmediatamente, con base en el argumento de incompatibilidad de personalidades (”mi vibra no les agradaba”), junto al intento de violación de domicilio, normalizada después de contactar a la Guardia Civil de Barcelona a través del número 112, hechos jurídicos ocurridos en mayo/2024;",
    "9. Varios correos electrónicos reiterados ignorados para que discutiéramos las cuestiones pertinentes a la convivencia de modo que tuviéramos la posibilidad de registrar la pauta y acta de los temas a ser discutidos, así como las deliberaciones de los cohabitantes, para que garantizáramos la armonía, el intento de realizar tal discusión de modo no rastreable en un bar cercano al domicilio, el hecho de que después de consumir mi café me sintiera mal y necesitara ayuda sanitaria/médica, el hecho de que los cohabitantes ignoraron mi aviso de incapacidad para continuar la conversación por motivos de salud, la negligencia en mi socorro inmediato, así como el intento de intimidación en ese mismo evento a través de gritos y escándalos en la calle, hechos jurídicos ocurridos en mayo/2024;",
    "10. De la privación de mi libertad de movimiento, manteniéndome bajo uso de fuerza en las premisas de la cocina común, mientras recogía mi entrega de almuerzo, en la pausa de almuerzo en mi jornada laboral, y el intento de intimidación, ocurrido durante 30 minutos, así como mi intento de llamar a las fuerzas del orden a través del 112, que comparecieron horas después, y de contactar el servicio de emergencia consular italiano en Barcelona, en función de la gravedad del crimen de secuestro, la conducción coercitiva, el impedimento criminal del goce pleno del derecho constitucional de libre movimiento, o habeas corpus, protocolado por el mismo, hechos jurídicos ocurridos en mayo/2024;",
    "11. De la privación del acceso a mi domicilio (habitación privada) mientras me duchaba, durante mi jornada laboral utilizando copia de la llave de la habitación ilegal en posesión ya sea del agente inmobiliario (que se escondió en las premisas hasta un momento posterior) o de una cohabitante, el proferimiento de ofensas de naturaleza análoga a tortura psicológica mientras me encontraba en el pasillo común, buscando ayuda de un profesional especialista en cerraduras; del intento de mantener ya sea a mí como al profesional que había llegado a las premisas para ayudarme a recuperar el acceso en situación de rehén a través del uso de fuerza y agresión física, así como mi intento de llamar a las fuerzas del orden a través del 112, que ignoraron la llamada, hechos ocurridos en mayo/2024.",
    "12. De la privación de mi libertad de movimiento, manteniéndome bajo uso de amenaza e intimidación en las premisas de mi habitación privada, durante 5 días, impidiendo, incluso, el suministro de recursos básicos, cuando del acto de encerrarme fuera de mi residencia utilizando una llave de acceso de la cual no poseo copia, cuando del recibimiento de dos entregas de compras de supermercado a través de la aplicación de logística Uber Eats, así como mi intento de llamar a las fuerzas del orden a través del 112, que ignoraron la llamada, así como los cuerpos diplomáticos de la República Italiana y de la República Federativa de Brasil, proporcionando relato de los hechos a sus respectivas V. Sas. Vicecónsules, a la comparecencia de dos agentes de la fuerza del orden a llamado de los cuerpos consulares pero que no detuvieron a los criminales, en función de una omisión flagrante, así como de mi llamada a las fuerzas del orden indicando con mayor asertividad emocional la naturaleza de lo ocurrido, que comparecieron con un escuadrón de operaciones especiales (5-8 agentes), y de mi intento de protocolar denuncia policial en la comisaría de los Mossos D’Esquadra de Horta-Guinardó, ignorada por el agente receptor, hechos jurídicos ocurridos en junio/2024.",
    "13. De la incapacidad de poder retornar a mi residencia por derecho, a través de intimidación, y de la privación de mis bienes materiales, con valor nominal y emocional a ser especificado en sección posterior;",
    "14. De lo que más conste en debido proveimiento de investigación policial, a ser solicitado a través de denuncia policial y al cuerpo competente (equivalente español al Fiscal General, o Ministerio Público);",
    "",
    "Les acuso por medio de esta de:",
    "",
    "Crímenes de agresión física, tortura y abusos psicológicos de vulnerables, estímulo al suicidio, sabotaje arbitrario de recursos de infraestructura básica (internet y electricidad), conducción coercitiva, detención ilícita en cautiverio privado, agravados por conocimiento de condición psíquica caracterizada por el DSM-5 F30.10, así como impedimento criminal del pleno goce del derecho constitucional de libre movimiento, o habeas corpus, así como falsedad ideológica, intento de violación de domicilio, intento de incriminación, asociación/organización criminal, negligencia al socorro emergencial, intimidación, violación de privacidad, violación de propiedad privada, ofensa, entre otros.",
    "",
    "Exigiendo: ",
    "",
    "Reparación por daños físicos: 119.600,00£",
    "",
    "Reparación por daños psicológicos: 300.000,00£",
    "",
    "Reparación por daños morales: 250.000,00£",
    "",
    "Reparación por daños materiales: 200.000,00£",
    "",
    "Detalle del argumento:",
    "",
    "El estado de vulnerabilidad social, para que califique la negligencia del cuidado profiláctico (del latín philiae) como abandono y/o abuso de vulnerable, no requiere de un cuadro clínico crónico, ni de interdicción legal por incapacidad o tutoría civil (por ejemplo, por minoría de edad, agravándose además como abuso de menores). Muchas veces la aparición de cuadros clínicos, agudos o crónicos, también pueden ser consecuencias directas o indirectas de estos mismos hechos jurídicos (F30.10), calificándolos como hechos agravados.",
    "",
    "La sospecha, además de los hechos antes mencionados, de interferencia dolosa en mis asuntos profesionales, sociales, culturales y emocionales, en forma de cancelación social (con, al menos, mis pares, mis amigos, mis familiares, mis empleadores, Arc.dev y Hunty Iberica SL), calificarían además, constitución de asociación delictiva en el caso del núcleo domiciliario. Al carecer de herramientas para la conducción de una investigación policial, delego la investigación de los hechos a los órganos competentes.",
    "",
    "La factura por los daños psicológicos se justifica en función de la regresión en la recuperación (F30.10), empeoramiento del cuadro e impedimento de encontrar la paz y la armonía para volver a mejorar.",
    "",
    "The bill for **moral damages is justified** based on being homeless, exposing myself publicly for food, more than 7 days without eating and being in ketosis, abandonment by family members, work difficulties.",
    "",
    "The bill for **material damages is justified** based on not being able to access my personal inventory which includes: family letters from the 1700s and 1800s, a photo of my dog, a complete music studio (Ableton Live Push 3, Deep Mind 6, Juno 6, MacMini, 2x Yamaha HS-8, Tibetan Bowl, a collection of over 400 vinyl records, including rarities, test presses, dubplates, limited numbered releases, and some unique copies in the entire European territory.",
    "",
    "Los hechos verificados deberán ser tratados extrajudicialmente a través de un pago inmediato de los valores mencionados en la exigencia, o en el juzgado penal de la ciudad de Barcelona.",
    "",
    "Londres, a 26 de agosto de 2024,",
    "",
    "Angelo.",
    ""
]

fs.writeFileSync(`./output/long-string.txt`,array.join('\n'), { flag: 'w' });
